export const HomeIcon = require('../../assets/images/home.png')
export const HomeFilledIcon = require('../../assets/images/homeFilled.png')
export const settingIcon = require('../../assets/images/setting.png')
export const settingFilledIcon = require('../../assets/images/settingFilled.png')
export const sunIcon = require('../../assets/images/sun.png')